# Gradle
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.java.installations.fromEnv=JDK_25
org.gradle.jvmargs=-Xmx2G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
org.gradle.parallel=true

group=com.example.library
version=0.1.0-SNAPSHOT

#Kotlin
kotlin.code.style=official

kotlin.native.ignoreDisabledTargets=true
