name: Publish Documentation

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Generate KDoc documentation
      run: ./gradlew :lib:dokkaGeneratePublicationHtml

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: lib/build/dokka/html

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: lib/build/dokka/html
        branch: gh-pages
        clean: true
